import type { Metadata } from 'next';
// import { Inter } from "next/font/google";
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import QueryProvider from '@/utils/queryProvider';

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

const queryClient = new QueryClient();

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-br">
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					fontSans.variable
				)}
			>
				<QueryProvider>{children}</QueryProvider>
			</body>
		</html>
	);
}
